from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('TinyGUI', src, depend = ['TinyGUI_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
