from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('TinyGUI', src, depend = ['PKG_USING_TinyGUI_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
