from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('TinyGUI', src, depend = ['PKG_USING_TinyGUI'], CPPPATH = CPPPATH)

Return('group')
